name: Astronomer CI - Create Deployment

on:
  push:
    branches: [create-new]
      # - "**"

# env:
#   ## Set your API token as a GitHub secret
#   ENV_VAR: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  create-new-deployment:
    runs-on: ubuntu-latest
    environment: astro-pov
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: install Astro
      run: |
        curl -sSL https://install.astronomer.io | sudo bash -s
    - name: deploy new deployment
      run: |
        DEPLOYMENT_ID = ${{ vars.DEPLOYMENT_ID }}
        DEPLOYMENT_NAME = "$(astro deployment inspect $DEPLOYMENT_ID --key configuration.name)"
        BRANCH_DEPLOYMENT_NAME=$BRANCH_NAME_$DEPLOYMENT_NAME
        BRANCH_DEPLOYMENT_NAME="$BRANCH_DEPLOYMENT_NAME// /_"

        astro deployment inspect $DEPLOYMENT_ID --template > deployment-preview-template.yaml 

        sed -i "s|  name:.*|  name: $BRANCH_DEPLOYMENT_NAME}|g"  deployment-preview-template.yaml

        # Create new preview Deployment based on the Deployment template file
        astro deployment create --deployment-file deployment-preview-template.yaml

        # Deploy new code to the deployment preview 
        astro deploy -n $BRANCH_DEPLOYMENT_NAME

