name: Astronomer CI - Create Deployment

on:
  push:
    branches: [test]
      # - "**"

# env:
#   ## Set your API token as a GitHub secret
#   ENV_VAR: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: astro-pov
    env:
      ## Sets DEV Deployment API credential as an environment variable
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.2
      with:
        action: create-deployment-preview
        deployment-id: clr79ik5w604621uxv9r0ioja0
    - name: Deploy code to preview
      uses: astronomer/deploy-action@v0.2
      with:
        action: deploy-deployment-preview
        deployment-id: clr79ik5w604621uxv9r0ioja0
    - name: Deploy code to main Deployment
      uses: astronomer/deploy-action@v0.2
      with:
        deployment-id: clr79ik5w604621uxv9r0ioja0