name: Astronomer CI - Create Deployment

on:
  push:
    branches: [create-new]

jobs:
  create-new-deployment:
    runs-on: ubuntu-latest
    environment: astro-pov
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Astro
      run: |
        curl -sSL https://install.astronomer.io | sudo bash -s
    - name: Create new deployment
      run: |
        export DEPLOYMENT_NAME=new_deployment

        # Create template of deployment to be copied with
        astro deployment inspect ${{ vars.DEPLOYMENT_ID }} --template > deployment-preview-template.yaml 

        # Add name to deployment template file
        sed -i "s|  name:.*|  name: $DEPLOYMENT_NAME|g"  deployment-preview-template.yaml

        # Create new preview deployment based on the deployment template file
        astro deployment create --deployment-file deployment-preview-template.yaml

        # Export new deployment ID
        echo "NEW_DEPLOYMENT_ID=$(astro deployment inspect --clean-output -n $BRANCH_DEPLOYMENT_NAME --key metadata.deployment_id)" >> $GITHUB_OUTPUT
