name: Astronomer CI - Create Deployment

on:
  push:
    branches: [test]
      # - "**"

env:
  ## Set your API token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.2
      with:
        action: create-deployment-preview
        deployment-id: test-github-actions-2
    - name: Deploy code to preview
      uses: astronomer/deploy-action@v0.2
      with:
        action: deploy-deployment-preview
        deployment-id: test-github-actions-2
    - name: Deploy code to main Deployment
      uses: astronomer/deploy-action@v0.2
      with:
        deployment-id: test-github-actions-2